In [1]:
import numpy as np

In [4]:
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x = np.ones((2,3), dtype=np.int64)
print(x)

[[1 1 1]
 [1 1 1]]


In [7]:
x = np.full((3,5), -1)
print(x)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [8]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
x = np.diag([10,15,60,90])
print(x)

[[10  0  0  0]
 [ 0 15  0  0]
 [ 0  0 60  0]
 [ 0  0  0 90]]


In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [14]:
x = np.arange(1, 14, 3)
print(x)

[ 1  4  7 10 13]


In [16]:
# for non integer steps
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [17]:
# for non integer steps
x = np.linspace(0, 25, 10, endpoint = False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [20]:
# to reshape arrays
x = np.arange(10)
print(x)

#reshape using np.reshape
y = np.reshape(x, (2,5))
print(y)

#reshae using object.reshape
z = x.reshape(2, 5)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
# create a 3x3 array with random floats between 0 and 1
x = np.random.random((3,3))
print(x)

[[0.11614467 0.58892452 0.33449466]
 [0.63692761 0.01661681 0.24407343]
 [0.2452431  0.11050017 0.44772861]]


In [24]:
# create a 3x3 array with random ints between 10 and 50
x = np.random.randint(10, 50, (3,3))
print(x)

[[47 32 15]
 [30 29 29]
 [40 21 15]]


In [27]:
# create a 10x10 array of random numbers drawn from a normal distribution
# with mean = 2 and stdev = 0.5
x = np.random.normal(2, 0.5, (10, 10))
print(x)

[[2.16516708 1.8861544  2.21052954 2.61431058 2.63360833 1.78133557
  2.59556519 1.76964751 2.34450494 2.2942877 ]
 [1.89008448 2.23395523 2.53525168 2.33477515 3.329814   2.14252023
  1.93751452 2.65080542 2.28524957 2.2532684 ]
 [1.38903378 2.14969657 1.94590251 0.98394097 1.89077481 1.61429844
  1.40834351 0.62750208 1.26977274 2.77952388]
 [2.52202235 1.23796131 1.80732182 1.98445228 1.5155505  2.88108187
  1.89835432 2.15919456 1.45782538 1.74919999]
 [2.29130164 2.14497301 2.22390817 1.75187817 1.34053938 2.34779925
  1.66176229 2.17566493 2.28684374 1.59925432]
 [1.70251832 1.73299983 2.11734017 1.40242617 2.02545345 1.74239861
  1.93241868 2.21515197 1.54541954 2.16276694]
 [2.09572225 1.67592924 2.1858188  2.06532583 1.12441863 0.73541769
  1.12110504 2.24461539 2.08287092 2.18835083]
 [2.68832932 2.14952903 1.96781459 1.85208274 1.014243   1.50510936
  2.06983456 2.67255381 2.24718806 2.08458963]
 [2.05709066 2.5035553  2.42733556 2.29491152 2.32293414 1.77080202
  2.76043514

In [28]:
print('mean: ', x.mean())
print('stdev: ', x.std())
print('max: ', x.max())
print('min: ', x.min())
print('# > 2: ', (x>2).sum())
print('# < 2: ', (x<2).sum())

mean:  2.0561239751475493
stdev:  0.5010306620999677
max:  3.329813995175477
min:  0.6275020802567124
# > 2:  59
# < 2:  41
