In [1]:
import numpy as np

In [2]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
z = x[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [4]:
# same way to do above
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [7]:
z = x[2, :]
print(z)

[11 12 13 14 15]


In [8]:
# doing it this way returns a rank 2 array
z = x[2:3, :]
print(z)

[[11 12 13 14 15]]


In [10]:
# slicing does NOT create a copy
x = np.arange(1,21).reshape(4,5)
print(x, '\n')

z = x[2:3, :]
print(z, '\n')

z[0][2] = -13
print(x, '\n')
print(z, '\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[11 12 13 14 15]] 

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12 -13  14  15]
 [ 16  17  18  19  20]] 

[[ 11  12 -13  14  15]] 



In [11]:
# use copy to make changes locally
x = np.arange(1,21).reshape(4,5)
print(x, '\n')

z = x[2:3, :].copy()
print(z, '\n')

z[0][2] = -13
print(x, '\n')
print(z, '\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[11 12 13 14 15]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 11  12 -13  14  15]] 



In [12]:
# to get diagonals
z = np.diag(x)
print(z)

[ 1  7 13 19]


In [13]:
# to get diagonals above or below
z = np.diag(x, 1)
print(z, '\n')

z = np.diag(x, -1)
print(z, '\n')

[ 2  8 14 20] 

[ 6 12 18] 



In [14]:
#to get unique values
x = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(x, '\n')

y = np.unique(x)
print(y)

[[1 2 3]
 [3 4 5]
 [5 6 7]] 

[1 2 3 4 5 6 7]
