In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
print(x>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [4]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [9]:
print(x[(x > 5) & (x < 18)])

[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [10]:
# set all values between 5 and 18 to 0
x[(x > 5) & (x < 18)] = 0
print(x)

[[ 0  1  2  3  4]
 [ 5  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 18 19]
 [20 21 22 23 24]]


In [12]:
#finding union, intersection and differences between arrays
x = np.array([1,2,3,4,5,6])
y = np.array([4,5,6,7,8,9])

print(np.union1d(x, y))
print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[1 2 3]


In [18]:
# sort
x = np.random.randint(1, 100, 10)
print(x)

[48 88 72 69 45 32 48 33 34 75]


In [19]:
# sort not in place
print(np.sort(x))
print(x)

# sort in place
x.sort()
print(x)

[32 33 34 45 48 48 69 72 75 88]
[48 88 72 69 45 32 48 33 34 75]
[32 33 34 45 48 48 69 72 75 88]


In [20]:
# sorting 2 d arrays
x = np.random.randint(1,100,(5,5))
print(x)

[[49 99 26 88 10]
 [69 90 63 61 48]
 [50 95 83 53  8]
 [61 12 10 19 59]
 [54 78 53 63 86]]


In [21]:
# sort by row
print(np.sort(x, axis=0))

[[49 12 10 19  8]
 [50 78 26 53 10]
 [54 90 53 61 48]
 [61 95 63 63 59]
 [69 99 83 88 86]]


In [22]:
# sort by column
print(np.sort(x, axis=1))

[[10 26 49 88 99]
 [48 61 63 69 90]
 [ 8 50 53 83 95]
 [10 12 19 59 61]
 [53 54 63 78 86]]
