In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(x.dtype)

int64


In [5]:
print(x.shape)

(5,)


In [9]:
y = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
print(y.shape)

(4, 3)


In [11]:
y.size

12

In [13]:
z = np.array(['hello', 'world'])
print(z.dtype)
print(z.shape)
print(z.size)

<U5
(2,)
2


In [14]:
z = np.array([1, 2, 'hello', 'world'])
print(z.dtype)
print(z.shape)
print(z.size)

<U21
(4,)
4


In [15]:
z = np.array([1, 2, 3.5, 4.1])
print(z.dtype)
print(z.shape)
print(z.size)

float64
(4,)
4


In [18]:
z = np.array([1, 2, 3.5, 4.1], dtype=np.int64)
print(z)
print(z.dtype)
print(z.shape)
print(z.size)

[1 2 3 4]
int64
(4,)
4


In [20]:
np.save('my_array', z)

In [21]:
a = np.load('my_array.npy')
print(a)

[1 2 3 4]
