In [1]:
import numpy as np

In [2]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [3]:
print('1st element:', x[0])
print('1st element from end:', x[-1])

1st element: 0
1st element from end: 4


In [4]:
# delete an element from array
x = np.arange(1,9)
print(x)
# delete elements at index 2 and 4
x = np.delete(x, [2,4])
print(x)

[1 2 3 4 5 6 7 8]
[1 2 4 6 7 8]


In [5]:
x = np.arange(1,17).reshape(4,4)
print(x, '\n')

# delete the second row
y = np.delete(x, 1, axis=0)
print(y, '\n')

# delete the first and last column
z = np.delete(x, [0,-1], axis=1)
print(z, '\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



In [6]:
# append element to rank 1 array
x = np.arange(10)
print(x)

x = np.append(x, 10)
print(x)

x = np.append(x, [-1,-2,-3])
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 -1 -2 -3]


In [10]:
# append elements to rank 2 array
x = np.arange(1,17).reshape(4,4)
print(x, '\n')

# append new row to x
x = np.append(x, [[17,18,19,20]], axis = 0)
print(x, '\n')

# append new column to x
x = np.append(x, [[-1], [-2], [-3], [-4], [-5]], axis=1)
print(x, '\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

[[ 1  2  3  4 -1]
 [ 5  6  7  8 -2]
 [ 9 10 11 12 -3]
 [13 14 15 16 -4]
 [17 18 19 20 -5]] 



In [11]:
# inserting in the middle of arrays
x = np.array([1,2,5,6,7])
print(x)

x = np.insert(x, 2, [3,4])
print(x)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [16]:
# inserting in 2d arrays
x = np.array([[1,2,3],[7,8,9]])
print(x, '\n')

x = np.insert(x, 1, [4,5,6], axis=0)
print(x, '\n')

x = np.insert(x, 2, [[-1,-2,-3]], axis=1)
print(x, '\n')

[[1 2 3]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  2 -1  3]
 [ 4  5 -2  6]
 [ 7  8 -3  9]] 



In [19]:
# stacking arrays
x = np.array([1,2])
y = np.array([[3,4], [5,6]])
print(x,'\n')
print(y,'\n')

z = np.vstack((x,y))
print(z,'\n')

[1 2] 

[[3 4]
 [5 6]] 

[[1 2]
 [3 4]
 [5 6]] 



In [21]:
z = np.hstack((x.reshape(2,1),y))
print(z,'\n')

[[1 3 4]
 [2 5 6]] 

