In [1]:
import numpy as np

In [2]:
x = np.arange(1,5)
y = np.arange(5,9)
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
# addition
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [4]:
# subtraction
print(x-y)
print(np.subtract(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [5]:
# multiplication
print(x * y)
print(np.multiply(x, y))

[ 5 12 21 32]
[ 5 12 21 32]


In [6]:
# division
print(x / y)
print(np.divide(x, y))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [7]:
# arithmetic on rank 2 arrays
x = np.arange(1,5).reshape(2,2)
y = np.arange(5,9).reshape(2,2)
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [8]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
# sqrt of array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
x = np.arange(1,10).reshape(3,3)
print(x)
# average of all numbers
print(np.mean(x))
# average of each column
print(np.mean(x, axis=0))
# average of each row
print(np.mean(x, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [18]:
x = np.arange(1,17).reshape(4,4)
# y = np.arange(1,9).reshape(2,4)
y = np.arange(1,5)
print(x)
print(y)
print(x+y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]
